import axios from 'axios';
import * as fs from 'fs';
import * as path from 'path';
import 'dotenv/config';
import { OddsApiGame, SabermetricProfile } from './types';

// --- Configuration ---
const ODDS_API_URL = 'https://api.the-odds-api.com/v4/sports/baseball_mlb/odds/';
const API_KEY = process.env.ODDS_API_KEY;
const TARGET_BOOKMAKERS = 'fanduel,draftkings,betmgm,bovada';
const MARKETS = 'h2h,spreads,totals';

/**
 * Fetches real-time market lines from The Odds API.
 */
async function fetchMarketOdds(): Promise<OddsApiGame[]> {
    try {
        const response = await axios.get<OddsApiGame[]>(ODDS_API_URL, {
            params: {
                apiKey: API_KEY,
                regions: 'us',
                markets: MARKETS,
                bookmakers: TARGET_BOOKMAKERS,
                oddsFormat: 'decimal' // QuantSlate requires decimal odds for math
            }
        });
        return response.data;
    } catch (error) {
        console.error('Error fetching market odds:', error);
        process.exit(1);
    }
}

/**
 * Retrieves underlying team metrics from the live JSON file generated by python.
 */
function fetchSabermetrics(teamName: string): SabermetricProfile | null {
    const dataPath = path.join(__dirname, 'real_sabermetrics.json');
    
    try {
        // Enforce file existence check to honor the strict 95% confidence protocol
        if (!fs.existsSync(dataPath)) {
            console.error(`Error: Data core missing at ${dataPath}. Execute your python script first.`);
            return null;
        }

        const rawData = fs.readFileSync(dataPath, 'utf-8');
        const liveDb: Record<string, SabermetricProfile> = JSON.parse(rawData);
        
        return liveDb[teamName] || null;
    } catch (error) {
        console.error(`Error reading sabermetrics data for ${teamName}:`, error);
        return null;
    }
}

/**
 * Parses and flattens the Odds API structure into the dense JSON
 * required by the QuantSlate AI Terminal.
 */
function compilePayload(games: OddsApiGame[]): any[] {
    const payload: any[] = [];
    const now = new Date();

    for (const game of games) {
        // 1. FILTER OUT ACTIVE LIVE GAMES
        // If a game started over 15 minutes ago, skip it to prevent stale stats vs live line bugs
        const commenceTime = new Date(game.commence_time);
        const timeDifferenceMins = (now.getTime() - commenceTime.getTime()) / (1000 * 60);
        if (timeDifferenceMins > 15) continue; 

        const homeMetrics = fetchSabermetrics(game.home_team);
        const awayMetrics = fetchSabermetrics(game.away_team);

        if (!homeMetrics || !awayMetrics) continue;

        const market_data: Record<string, any> = {};
        
        for (const bookie of game.bookmakers) {
            market_data[bookie.key] = {};

            // 2. ROBUST H2H EXTRACTION
            const h2h = bookie.markets.find(m => m.key === 'h2h');
            if (h2h && h2h.outcomes.length === 2) {
                const homeOutcome = h2h.outcomes.find(o => o.name === game.home_team);
                const awayOutcome = h2h.outcomes.find(o => o.name === game.away_team);

                // Guardrail: Skip if odds are wildly outside normal pre-match baseball boundaries (< 1.1 or > 5.0)
                if (homeOutcome && awayOutcome) {
                    if (homeOutcome.price > 5.0 || awayOutcome.price > 5.0) {
                        console.warn(`[Vig Warning] Skipping highly anomalous outlier line for ${game.home_team}: ${homeOutcome.price} / ${awayOutcome.price}`);
                        continue; 
                    }
                    market_data[bookie.key].home_ml = homeOutcome.price;
                    market_data[bookie.key].away_ml = awayOutcome.price;
                }
            }

            // 3. ROBUST SPREADS EXTRACTION
            const spreads = bookie.markets.find(m => m.key === 'spreads');
            if (spreads && spreads.outcomes.length === 2) {
                const homeSpread = spreads.outcomes.find(o => o.name === game.home_team);
                const awaySpread = spreads.outcomes.find(o => o.name === game.away_team);

                if (homeSpread && awaySpread) {
                    market_data[bookie.key].home_spread_odd = homeSpread.price;
                    market_data[bookie.key].home_spread_point = homeSpread.point;
                    market_data[bookie.key].away_spread_odd = awaySpread.price;
                    market_data[bookie.key].away_spread_point = awaySpread.point;
                }
            }

            // 4. ROBUST TOTALS EXTRACTION
            const totals = bookie.markets.find(m => m.key === 'totals');
            if (totals && totals.outcomes.length === 2) {
                const overOutcome = totals.outcomes.find(o => o.name.toLowerCase() === 'over');
                const underOutcome = totals.outcomes.find(o => o.name.toLowerCase() === 'under');

                if (overOutcome && underOutcome) {
                    market_data[bookie.key].total_over_odd = overOutcome.price;
                    market_data[bookie.key].total_under_odd = underOutcome.price;
                    market_data[bookie.key].total_point = overOutcome.point;
                }
            }
        }

        // Only append matchups that contain successfully structured market variables
        if (Object.keys(market_data).length > 0) {
            payload.push({
                matchup: `${game.away_team} @ ${game.home_team}`,
                commence_time: game.commence_time,
                market_data,
                sabermetrics: {
                    away_starter: awayMetrics.starter,
                    home_starter: homeMetrics.starter,
                    away_offense: awayMetrics.offense,
                    home_offense: homeMetrics.offense,
                    park_factor: homeMetrics.park_factor
                }
            });
        }
    }

    return payload;
}

// --- Execution ---
async function run() {
    console.log('Fetching market odds...');
    const games = await fetchMarketOdds();
    
    console.log('Merging live local sabermetrics and compiling payload...');
    const finalPayload = compilePayload(games);

    const outputPath = path.join(__dirname, 'quantslate_payload.json');
    fs.writeFileSync(outputPath, JSON.stringify(finalPayload, null, 2));

    console.log(`\nSuccess. Processed ${finalPayload.length} valid games with verified on-field metrics.`);
    console.log(`Payload saved to: ${outputPath}`);
    console.log('\nCommand to copy payload to clipboard:');
    console.log('cat quantslate_payload.json | pbcopy');
}

run();